version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    stdin_open: true
    tty: true
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banking_api
      PORT: 3306
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 5
    cap_add:
      - SYS_NICE

  # Backend (Node.js + Express + Sequelize)
  backend:
    stdin_open: true
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 3001
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: banking_api
      DB_PORT: 3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 30s
      retries: 5
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend (React + Tailwind)
  frontend:
    stdin_open: true
    tty: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      PORT: 3000
      REACT_APP_BASE_URL: http://localhost:3001
      REACT_APP_BASE_URL_ORIGIN: http://localhost:3000
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5