version: '3.9'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    env_file:
      - .env
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 60s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql

  # Backend (Node.js + Express + Sequelize)
  backend:
    stdin_open: true
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 3001
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: banking_api
      DB_PORT: 3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      interval: 10s
      timeout: 60s
      retries: 5
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend (React + Tailwind)
  frontend:
    stdin_open: true
    tty: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      PORT: 3000
      REACT_APP_BASE_URL: http://localhost:3001
      REACT_APP_BASE_URL_ORIGIN: http://localhost:3000
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      interval: 10s
      timeout: 60s
      retries: 5

volumes:
  db_data:
    driver: local