version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3002:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banking_api
      PORT: 3001
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 5
    cap_add:
      - SYS_NICE

  # Backend (Node.js + Express + Sequelize)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 3001
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD:
      DB_NAME: banking_api
      DB_PORT: 3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 30s
      retries: 5
    volumes:
      - ./backend:/app
      - /app/node_modules